GROQ_API_KEY = "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"
AVWX_API_KEY= "jLX2iQWBGYttAwYBxiFCUc_4ljrbNOqCNvHe5hjtS8o"
OPENSKY_USERNAME="sami___ag"
OPENSKY_PASSWORD="716879Sami."
WINDY_API_KEY="ymAvnkZvsbZpxgMVlHabWuDIG6ZgHsJd"
