GROQ_API_KEY = "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"
AVWX_API_KEY= "jLX2iQWBGYttAwYBxiFCUc_4ljrbNOqCNvHe5hjtS8o"
OPENSKY_USERNAME="sami___ag"
OPENSKY_PASSWORD="716879Sami."
WINDY_API_KEY="ymAvnkZvsbZpxgMVlHabWuDIG6ZgHsJd"
